services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: easylend_api
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379/0
    networks:
      - backend-net

  database:
    image: postgres:17
    container_name: postgres
    restart: unless-stopped
    ports:
      # Alleen bereikbaar vanaf de server zelf (of via SSH Tunnel)
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgresql/data  # <- Named Volume!
    shm_size: 256mb
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend-net
      - management-net

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: unless-stopped
    ports:
      - "48050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin_data:/var/lib/pgadmin  # <- Named Volume!
    networks:
      - management-net

  redis:
    image: redis:7-alpine
    container_name: redis_cache
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes
    volumes:
      - redis_data:/data  # <- Named Volume!
    networks:
      - backend-net

  sqlbak:
    image: pranasnet/sqlbak
    container_name: sqlbak
    restart: unless-stopped
    environment:
      - sqlbak_key=${SQLBAK_TOKEN}
    volumes:
      - sqlbak_data:/opt/sqlbak  # <- Named Volume!
    networks:
      - backend-net

# Hier definiÃ«ren we de Named Volumes voor Docker
volumes:
  pg_data:
  pgadmin_data:
  redis_data:
  sqlbak_data:

networks:
  backend-net:
    driver: bridge
  management-net:
    driver: bridge