services:
  database:
    image: postgres:17
    container_name: postgres
    restart: unless-stopped
    ports:
      # Alleen bereikbaar vanaf de server zelf (of via SSH Tunnel)
      - 127.0.0.1:5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    shm_size: 256mb
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend-net
      - management-net
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: unless-stopped
    ports:
      - 48050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    networks:
      - management-net
  redis:
    image: redis:7-alpine
    container_name: redis_cache
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes
    volumes:
      - ./redis_data:/data
    networks:
      - backend-net
  sqlbak:
    image: pranasnet/sqlbak
    container_name: sqlbak
    restart: unless-stopped
    environment:
      - sqlbak_key=${SQLBAK_TOKEN}
    volumes:
      - ./sqlbak_volume:/opt/sqlbak
    networks:
      - backend-net
networks:
  backend-net:
    driver: bridge
  management-net:
    driver: bridge
